language: node_js
node_js:
- '9'
script:
- echo "npm test temporarily disabled"
deploy:
  provider: heroku
  app: application-gestion-easport
  api_key:
      secure: "jaqQ7lfF5VBAtUSdnEG6uaWjHO6hFOh0O2uASV/zK89KGfVvqdqtd4MRpdnCJDzQ36uX/zs3htuOV9PVhztDR4894ugGYQwj01Qcv3USzjKS7A9Jaee9guNVpM7SNaeBN69rvKSqz/2AvnjPLRfvt5t++oku+iPK4gU+QAhs0pRpaWKi5Uk+o5Rq0j62B0Boot/zW38FdVdNHTC65NNaUjDWxykCYa8Tru7HkyaHTaaiShGqoyjs64rDti5+CEXrm7Unk7vTLM0QyXIg0hDGc2PoAiZ0GS9pjRuaK76B1rjygzt1orfGMqkU4+9gVW6BQNz45kxJwosU4GTeU8cIM+yEpjD9hqZ/TQyaLVv++4gZb8hXs5pJIMyMDY0rzWcJD4yfh7kmEvnf0PTA/TQ09JGo5MtO/Yq0ZT80I2FQZidGtXQOoE+KR429NJk7L7y+8+LtVdXXb0vr1WtnCQFw4cHmfQRoZhmonBD5J9qwgagT0nxkMny3AuMyHYy5MTMYpXvgRlK9P5XvvylUa72cyQQGC/RKLtjZTw5QsVha8X4bEoZNRbzUHxOYkf0LffO2qWp7xoxThSwQyiUQkR0HOClGdVKdRQxg/m8IFTflUzcqZySKISsm5SF0E2VcNctTXZsU2H7VxAxBl0cX5wFHMWZ+RGIdBKgLy0ALeyGeRIc="
service:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -U postgres -d travis_ci_test -a -f ./BDD/db.sql
