language: node_js
node_js:
- '9'
script:
- cd nodejs-minimal-boilerplate
- yarn
- yarn run test
deploy:
  provider: heroku
  app: application-gestion-easport
  api_key:
    secure: jwjWgc6b4wSIM3k5HUCwr/qfCWCDDIrDDNoo3AjJaU40scAytk+I9FTG63UssSOhav/Ips6aoXjx1paMQ29/wLw3y72Fy4hreVIsNQJNXe1xPeuZB5ehY7BVMKiioTQKBDTKMhCMWCmeCMBOHwy2EQclJT8eLzOWe6LFmqp8yL3StrxVvJ55uB22Iktsr5QUN52DRkuiote8Jz2d+p5N/25IZoPEelD1bdx4H6qkuOu2SopbSPIZBW4pcEc6Ta5upuqiehdHbxEFnN6RWdc9bvaI4yjMbTaHSBQBvl7ZMV6qNfijXf0qaRegcc6tET+v3AgMA4go26bWCsqwJAJ5oIBpi5ZooZepVHPuF0znEPGfzCjG3UOntxrFibYtIulECQ5MofOjplhL/d56x9kgZkU6tNn6nSroqwHbmI0ZCSGviZX/QbZjflwD6Jgd2lCdmwN+scauWTb9gXjZfqal8UJkCGJ/5ycIaYnSp0FAYStz59V14S3BXq0rKKDV3pxwqynlBR202cmlU3N2Qtt9lvsefmreKR2VrIcLIKLvAZSCgacdJY3XvFLTXTNNswZVfuYFOlLgp4af8lPysEISqTZzKPMe+qo6korhqn3rUe7+j1wd7JjHnUH6aNoo/LKwIKrpGvdEAQJcCkHm4G9eSxjY7q2NXKOybAIm0YIX2K8=
service:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -Wblacksalami -a -f ./BDD/db.sql