language: node_js
node_js:
- '9'
script:
- echo "npm test temporarily disabled"
deploy:
  provider: heroku
  app: application-gestion-easport
  api_key:
    secure: "58a77282-1e4d-4467-8be4-52e6749bec54"
service:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -a -f ./BDD/db.sql