language: node_js
node_js:
- '9'
script:
- echo "npm test temporarily disabled"
deploy:
  provider: heroku
  app: application-gestion-easport
  api_key:
    secure: 0ee0c70a-5322-4680-be60-4f62c106c1c6
service:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -a -f ./BDD/db.sql